### ISSUE TITLE
WinterGOAHistorical::query_run_time parameter

### ISSUE THREAD

**Issue by mike-levine** [noaa-afsc-mace/WinterGOAHistorical#3]
Hey @abigailatsea 
Minor (very minor) request: Would you mind changing the name of the value `query_run_time ` that is included with your data? There's nothing wrong with it, but it causes a conflict with the reports where you have two `query_run_time ` objects, and its hard to know which is which. Maybe change to `historical_query_run_time` or something?

**Comment by abigailatsea** [comment]
Hi Mike-
I'm trying to fix this but cannot seem to get the package to rebuild with that renamed file. Stay tuned.

**Comment by abigailatsea** [comment]
Hey @mike-levine -
Fixed the variable name so it's now "historical_query_run_time". Can you pull and test for me please?

**Comment by mike-levine** [comment]
Yep! I re-installed package and that is now in there. Thanks!

**Comment by abigailatsea** [comment]
yay!
